server:
  port: 9008  #服务访问端口号
spring:
  application:
    name: power-user #指定服务名
  datasource:  #数据库链接
    url: jdbc:mysql://192.168.127.128:3306/tensquare_user?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: true
  #设置时区为东八区
  jackson:
    time-zone: GMT+8
# Mybatis-Plus 配置
mybatis-plus:
  # mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.power.user.pojo
  global-config:
    id-type: 1 #0:数据库ID自增 1:用户输入id
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启延时加载，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用