server:
  port: 9004  #服务访问端口号
spring:
  application:
    name: power-article #指定服务名
  datasource:  #数据库链接
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.127.128:3306/tensquare_article?characterEncoding=utf-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: true
  data:
    mongodb:
      host: 192.168.127.128
      port: 27017
      database: comment
      #uri: mongodb:192.168.127.128/27017
#设置时区为东八区
  jackson:
    time-zone: GMT+8
  redis:
    host: 192.168.127.128
    port: 6379
# Mybatis-Plus 配置
mybatis-plus:
# mapper-locations: classpath:/mapper/*Mapper.xml
#实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.power.article.pojo
  global-config:
    id-type: 1 #0:数据库ID自增 1:用户输入id
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启延时加载，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true